events {}
http {
  upstream article {
    server article-api-1:8080;
    server article-api-2:8080;
    server article-api-3:8080;
  }
  server {
    listen 80;
    location / {
      proxy_pass http://article;
      proxy_set_header Host $http_host;
    }
  }
}
